# Generated by Django 4.2.7 on 2025-07-31 12:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('telefon_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon numarası +90 veya 05 ile başlamalıdır.', regex='^(\\+90|05)\\d{10,}$')], verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-posta')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('cinsiyet', models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadin', 'Kadın'), ('Diger', 'Diğer')], max_length=10, null=True, verbose_name='Cinsiyet')),
                ('adres', models.TextField(blank=True, max_length=500, null=True, verbose_name='Adres')),
                ('acil_durum_kisi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acil Durum Kişisi')),
                ('acil_durum_telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Acil Durum Telefonu')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasta_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
            },
        ),
    ]
