# Generated by Django 4.2.7 on 2025-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='İlaç, besin, polen vb. alerjilerinizi belirtiniz', null=True, verbose_name='Alerjiler'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A Rh+'), ('A-', 'A Rh-'), ('B+', 'B Rh+'), ('B-', 'B Rh-'), ('AB+', 'AB Rh+'), ('AB-', 'AB Rh-'), ('O+', 'O Rh+'), ('O-', 'O Rh-')], max_length=3, null=True, verbose_name='Kan Grubu'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Diyabet, hipertansiyon, astım vb. kronik hastalıkları belirtiniz', null=True, verbose_name='Kronik Hastalıklar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='son_giris',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Giriş'),
        ),
    ]
