# Generated by Django 4.2.7 on 2025-07-31 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(default='genel', max_length=50, verbose_name='Kategori')),
                ('ayar_adi', models.CharField(max_length=100, unique=True, verbose_name='Ayar Adı')),
                ('ayar_degeri', models.TextField(blank=True, null=True, verbose_name='Ayar Değeri')),
                ('veri_tipi', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('date', 'Date')], default='string', max_length=20, verbose_name='Veri Tipi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('herkese_acik', models.BooleanField(default=False, verbose_name='Herkese Açık Mı')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('guncelleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
                'ordering': ['kategori', 'ayar_adi'],
            },
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonderen_tip', models.CharField(choices=[('doktor', 'Doktor'), ('bakici', 'Bakıcı'), ('sistem', 'Sistem'), ('admin', 'Admin')], max_length=20, verbose_name='Gönderen Tipi')),
                ('alici_tip', models.CharField(choices=[('hasta', 'Hasta'), ('doktor', 'Doktor'), ('bakici', 'Bakıcı')], default='hasta', max_length=20, verbose_name='Alıcı Tipi')),
                ('bildirim_tipi', models.CharField(choices=[('ilac_hatirlatma', 'İlaç Hatırlatması'), ('randevu_onay', 'Randevu Onayı'), ('randevu_red', 'Randevu Reddi'), ('randevu_hatirlatma', 'Randevu Hatırlatması'), ('randevu_talebi', 'Randevu Talebi'), ('bakici_atama', 'Bakıcı Ataması'), ('ilac_eklendi', 'İlaç Eklendi'), ('genel', 'Genel Bildirim'), ('acil', 'Acil Durum'), ('bilgi_guncelleme', 'Bilgi Güncelleme')], max_length=50, verbose_name='Bildirim Tipi')),
                ('oncelik', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('acil', 'Acil')], default='normal', max_length=20, verbose_name='Öncelik')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('gonderim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu Mu')),
                ('okunma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('sms_gonderildi', models.BooleanField(default=False, verbose_name='SMS Gönderildi Mi')),
                ('sms_gonderim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='SMS Gönderim Tarihi')),
                ('email_gonderildi', models.BooleanField(default=False, verbose_name='Email Gönderildi Mi')),
                ('email_gonderim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Email Gönderim Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldigi_bildirimler', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('gonderen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gonderdigi_bildirimler', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bildirimleri', to='medications.ilac', verbose_name='İlgili İlaç')),
                ('randevu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bildirimleri', to='appointments.appointment', verbose_name='İlgili Randevu')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-gonderim_tarihi'],
                'indexes': [models.Index(fields=['alici', 'okundu'], name='notificatio_alici_i_7326d3_idx'), models.Index(fields=['bildirim_tipi'], name='notificatio_bildiri_e00051_idx'), models.Index(fields=['oncelik'], name='notificatio_oncelik_166b21_idx'), models.Index(fields=['gonderim_tarihi'], name='notificatio_gonderi_b648db_idx')],
            },
        ),
    ]
