# Generated by Django 4.2.7 on 2025-08-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='sms_durum',
            field=models.CharField(blank=True, choices=[('pending', 'Beklemede'), ('sent', 'Gönderildi'), ('delivered', 'Teslim Edildi'), ('failed', 'Başarısız')], default='pending', max_length=20, null=True, verbose_name='SMS Durumu'),
        ),
        migrations.AddField(
            model_name='bildirim',
            name='sms_hata_mesaji',
            field=models.TextField(blank=True, null=True, verbose_name='SMS Hata Mesajı'),
        ),
    ]
