# Generated by Django 4.2.7 on 2025-07-31 12:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('randevu_id', models.AutoField(db_column='RandevuID', primary_key=True, serialize=False, verbose_name='Randevu ID')),
                ('randevu_tarihi', models.DateTimeField(db_column='RandevuTarihi', verbose_name='Randevu Tarihi')),
                ('randevu_suresi', models.IntegerField(db_column='RandevuSuresi', default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='Randevu Süresi (Dakika)')),
                ('durum', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Onaylandi', 'Onaylandı'), ('Reddedildi', 'Reddedildi'), ('Tamamlandi', 'Tamamlandı'), ('Iptal', 'İptal')], db_column='Durum', default='Beklemede', max_length=20, verbose_name='Durum')),
                ('randevu_tipi', models.CharField(choices=[('Muayene', 'Muayene'), ('Kontrol', 'Kontrol'), ('Konsultasyon', 'Konsültasyon')], db_column='RandevuTipi', default='Muayene', max_length=50, verbose_name='Randevu Tipi')),
                ('hasta_notlari', models.TextField(blank=True, db_column='HastaNotlari', max_length=1000, null=True, verbose_name='Hasta Notları')),
                ('doktor_notlari', models.TextField(blank=True, db_column='DoktorNotlari', max_length=1000, null=True, verbose_name='Doktor Notları')),
                ('online_randevu_mu', models.BooleanField(db_column='OnlineRandevuMu', default=False, verbose_name='Online Randevu Mu')),
                ('olusturulma_tarihi', models.DateTimeField(db_column='OlusturulmaTarihi', default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, db_column='GuncellenmeTarihi', verbose_name='Güncellenme Tarihi')),
                ('doktor', models.ForeignKey(db_column='DoktorID', on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='doctors.doctor', verbose_name='Doktor')),
                ('hasta', models.ForeignKey(db_column='HastaID', on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='patients.patient', verbose_name='Hasta')),
                ('onaylayan_kullanici', models.ForeignKey(blank=True, db_column='OnaylayanKullanici', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onayladigi_randevular', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan Kullanıcı')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'db_table': 'Randevular',
                'ordering': ['-randevu_tarihi'],
            },
        ),
    ]
