# Generated by Django 4.2.7 on 2025-07-31 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilac_adi', models.CharField(max_length=200, verbose_name='İlaç Adı')),
                ('etken_madde', models.CharField(blank=True, max_length=200, null=True, verbose_name='Etken Madde')),
                ('dozaj', models.CharField(help_text='Örn: 500mg, 1 tablet, 5ml', max_length=50, verbose_name='Dozaj')),
                ('kullanim_sikligi', models.CharField(help_text='Örn: Günde 3 kez, 12 saatte bir, 8 saatte bir', max_length=100, verbose_name='Kullanım Sıklığı')),
                ('yemek_iliskisi', models.CharField(blank=True, choices=[('yemekten_once', 'Yemekten Önce'), ('yemekten_sonra', 'Yemekten Sonra'), ('yemekle_birlikte', 'Yemekle Birlikte'), ('ac_karnina', 'Aç Karnına'), ('farketmez', 'Farketmez')], max_length=20, null=True, verbose_name='Yemek İlişkisi')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('kullanim_talimatlari', models.TextField(blank=True, null=True, verbose_name='Kullanım Talimatları')),
                ('yan_etkiler', models.TextField(blank=True, null=True, verbose_name='Yan Etkiler')),
                ('uyarilar', models.TextField(blank=True, null=True, verbose_name='Uyarılar')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recete_ettigi_ilaclar', to='doctors.doctor', verbose_name='Doktor')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilac_alim_gecmisi', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'İlaç',
                'verbose_name_plural': 'İlaçlar',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='IlacAlimGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planlanan_alim_tarihi', models.DateTimeField(verbose_name='Planlanan Alım Tarihi')),
                ('gercek_alim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Alım Tarihi')),
                ('alim_durumu', models.CharField(choices=[('beklemede', 'Beklemede'), ('alindi', 'Alındı'), ('atlanmis', 'Atlanmış'), ('gecikme', 'Gecikme')], default='beklemede', max_length=20, verbose_name='Alım Durumu')),
                ('gecikme_suresi', models.PositiveIntegerField(default=0, verbose_name='Gecikme Süresi (Dakika)')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('hatirlatma_gonderildi', models.BooleanField(default=False, verbose_name='Hatırlatma Gönderildi Mi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilaclar', to='patients.patient', verbose_name='Hasta')),
                ('ilac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alim_gecmisi', to='medications.ilac', verbose_name='İlaç')),
            ],
            options={
                'verbose_name': 'İlaç Alım Geçmişi',
                'verbose_name_plural': 'İlaç Alım Geçmişleri',
                'ordering': ['-planlanan_alim_tarihi'],
            },
        ),
    ]
