# Generated by Django 4.2.7 on 2025-07-31 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doktor_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Doktor ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('uzmanlik', models.CharField(max_length=100, verbose_name='Uzmanlık')),
                ('diploma_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diploma Numarası')),
                ('telefon_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-posta')),
                ('calisma_saatleri', models.TextField(blank=True, help_text='JSON formatında: {"pazartesi": "09:00-17:00", ...}', null=True, verbose_name='Çalışma Saatleri')),
                ('muayenehane_adresi', models.TextField(blank=True, max_length=500, null=True, verbose_name='Muayenehane Adresi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doktor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktorlar',
            },
        ),
    ]
