# Generated by Django 4.2.7 on 2025-07-31 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Şablon Adı')),
                ('template_id', models.CharField(max_length=100, verbose_name='Huawei Template ID')),
                ('message_template', models.TextField(help_text='Parametreler {0}, {1} şeklinde kullanılır', verbose_name='Mesaj Şablonu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('category', models.CharField(default='General', max_length=50, verbose_name='Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'SMS Şablonu',
                'verbose_name_plural': 'SMS Şablonları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('kategori', models.CharField(db_column='Kategori', default='Genel', max_length=50, verbose_name='Kategori')),
                ('ayar_adi', models.CharField(db_column='AyarAdi', max_length=100, unique=True, verbose_name='Ayar Adı')),
                ('ayar_degeri', models.TextField(blank=True, db_column='AyarDegeri', null=True, verbose_name='Ayar Değeri')),
                ('veri_tipi', models.CharField(choices=[('String', 'String'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('JSON', 'JSON'), ('Date', 'Date')], db_column='VeriTipi', default='String', max_length=20, verbose_name='Veri Tipi')),
                ('aciklama', models.TextField(blank=True, db_column='Aciklama', max_length=500, null=True, verbose_name='Açıklama')),
                ('is_public', models.BooleanField(db_column='IsPublic', default=False, verbose_name='Herkese Açık Mı')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt', verbose_name='Güncellenme Tarihi')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UpdatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
                'db_table': 'SistemAyarlari',
                'ordering': ['kategori', 'ayar_adi'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.AutoField(db_column='LogID', primary_key=True, serialize=False, verbose_name='Log ID')),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_column='LogLevel', default='INFO', max_length=20, verbose_name='Log Seviyesi')),
                ('kategori', models.CharField(db_column='Kategori', max_length=50, verbose_name='Kategori')),
                ('mesaj', models.TextField(db_column='Mesaj', verbose_name='Mesaj')),
                ('ip_adresi', models.CharField(blank=True, db_column='IPAdresi', max_length=50, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, db_column='UserAgent', max_length=500, null=True, verbose_name='User Agent')),
                ('ek_bilgiler', models.TextField(blank=True, db_column='EkBilgiler', null=True, verbose_name='Ek Bilgiler (JSON)')),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sistem Logu',
                'verbose_name_plural': 'Sistem Logları',
                'db_table': 'SistemLoglari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['log_level'], name='SistemLogla_LogLeve_88618e_idx'), models.Index(fields=['kategori'], name='SistemLogla_Kategor_f81ade_idx'), models.Index(fields=['created_at'], name='SistemLogla_Created_668f4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=15, verbose_name='Alıcı Telefon')),
                ('message', models.TextField(max_length=1000, verbose_name='Mesaj İçeriği')),
                ('message_type', models.CharField(default='General', help_text='IlacHatirlatma, RandevuOnay, etc.', max_length=50, verbose_name='Mesaj Tipi')),
                ('template_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Template ID')),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Huawei Message ID')),
                ('status', models.CharField(choices=[('Pending', 'Beklemede'), ('Sent', 'Gönderildi'), ('Failed', 'Başarısız'), ('Delivered', 'Teslim Edildi'), ('Rejected', 'Reddedildi')], default='Pending', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Edilme Tarihi')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Tekrar Deneme Sayısı')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Maksimum Tekrar Deneme')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Sonraki Deneme Zamanı')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı Kullanıcı')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='sms_service_status_dbcca9_idx'), models.Index(fields=['created_at'], name='sms_service_created_142963_idx'), models.Index(fields=['recipient_phone'], name='sms_service_recipie_50ad07_idx'), models.Index(fields=['message_type'], name='sms_service_message_4a8825_idx')],
            },
        ),
    ]
