# Generated by Django 4.2.7 on 2025-08-04 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAlarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100, verbose_name='Hasta Adı')),
                ('patient_phone', models.CharField(max_length=15, verbose_name='Hasta Telefon')),
                ('alarm_type', models.CharField(choices=[('medication', 'İlaç Hatırlatması'), ('appointment', 'Randevu Hatırlatması'), ('checkup', 'Kontrol Hatırlatması'), ('general', 'Genel Hatırlatma')], max_length=20, verbose_name='Alarm Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Alarm Başlığı')),
                ('message', models.TextField(verbose_name='Mesaj İçeriği')),
                ('alarm_time', models.TimeField(verbose_name='Alarm Saati')),
                ('alarm_date', models.DateField(blank=True, null=True, verbose_name='Alarm Tarihi')),
                ('repeat_type', models.CharField(choices=[('once', 'Bir Kez'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('custom', 'Özel')], default='once', max_length=20, verbose_name='Tekrar Tipi')),
                ('custom_days', models.CharField(blank=True, help_text='1,2,3,4,5 (Pazartesi-Cuma)', max_length=20, verbose_name='Özel Günler')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('paused', 'Duraklatıldı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('total_sent', models.IntegerField(default=0, verbose_name='Toplam Gönderim')),
                ('successful_sent', models.IntegerField(default=0, verbose_name='Başarılı Gönderim')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Son Gönderim')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Sonraki Çalışma')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_alarms', to=settings.AUTH_USER_MODEL, verbose_name='Doktor')),
                ('patient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_alarms', to=settings.AUTH_USER_MODEL, verbose_name='Hasta Kullanıcı')),
            ],
            options={
                'verbose_name': 'Doktor Alarmı',
                'verbose_name_plural': 'Doktor Alarmları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlarmHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gönderim Zamanı')),
                ('success', models.BooleanField(default=False, verbose_name='Başarılı')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sms_service.doctoralarm', verbose_name='Alarm')),
                ('sms_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_service.smslog', verbose_name='SMS Log')),
            ],
            options={
                'verbose_name': 'Alarm Geçmişi',
                'verbose_name_plural': 'Alarm Geçmişleri',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='doctoralarm',
            index=models.Index(fields=['doctor', 'status'], name='sms_service_doctor__a6e059_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoralarm',
            index=models.Index(fields=['alarm_time'], name='sms_service_alarm_t_ba6a84_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoralarm',
            index=models.Index(fields=['next_run'], name='sms_service_next_ru_2572d1_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoralarm',
            index=models.Index(fields=['status'], name='sms_service_status_0bc026_idx'),
        ),
    ]
