# Generated by Django 4.2.7 on 2025-07-31 12:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('bakici_id', models.CharField(db_column='BakiciID', max_length=20, primary_key=True, serialize=False, verbose_name='Bakıcı ID')),
                ('ad', models.CharField(db_column='Ad', max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(db_column='Soyad', max_length=50, verbose_name='Soyad')),
                ('telefon_no', models.CharField(blank=True, db_column='TelefonNo', max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=100, null=True, verbose_name='E-posta')),
                ('deneyim', models.IntegerField(db_column='Deneyim', default=0, help_text='Yıl cinsinden deneyim', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deneyim (Yıl)')),
                ('egitim_durumu', models.CharField(blank=True, db_column='EgitimDurumu', max_length=100, null=True, verbose_name='Eğitim Durumu')),
                ('sertifika_numarasi', models.CharField(blank=True, db_column='SertifikaNumarasi', max_length=50, null=True, verbose_name='Sertifika Numarası')),
                ('maksimum_hasta_sayisi', models.IntegerField(db_column='MaksimumHastaSayisi', default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Maksimum Hasta Sayısı')),
                ('saatlik_ucret', models.DecimalField(blank=True, db_column='SaatlikUcret', decimal_places=2, max_digits=10, null=True, verbose_name='Saatlik Ücret (TL)')),
                ('calisma_bolgeleri', models.TextField(blank=True, db_column='CalismaBolgeleri', help_text='JSON array formatında: ["Kadıköy", "Üsküdar"]', null=True, verbose_name='Çalışma Bölgeleri')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True, verbose_name='Aktif Mi')),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bakıcı',
                'verbose_name_plural': 'Bakıcılar',
                'db_table': 'Bakicilar',
            },
        ),
        migrations.CreateModel(
            name='CaregiverPatientMapping',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('baslangic_tarihi', models.DateField(db_column='BaslangicTarihi', verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, db_column='BitisTarihi', null=True, verbose_name='Bitiş Tarihi')),
                ('calisma_saatleri', models.TextField(blank=True, db_column='CalismaSaatleri', help_text='JSON formatında: {"pazartesi": "10:00-14:00", ...}', null=True, verbose_name='Çalışma Saatleri')),
                ('hizmet_tipi', models.CharField(choices=[('Genel Bakım', 'Genel Bakım'), ('Tıbbi Bakım', 'Tıbbi Bakım'), ('Fizyoterapi Yardımı', 'Fizyoterapi Yardımı')], db_column='HizmetTipi', default='Genel Bakım', max_length=100, verbose_name='Hizmet Tipi')),
                ('notlar', models.TextField(blank=True, db_column='Notlar', max_length=1000, null=True, verbose_name='Notlar')),
                ('haftalik_saat', models.IntegerField(db_column='HaftalikSaat', default=40, verbose_name='Haftalık Saat')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True, verbose_name='Aktif Mi')),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt', verbose_name='Güncellenme Tarihi')),
                ('bakici', models.ForeignKey(db_column='BakiciID', on_delete=django.db.models.deletion.CASCADE, to='caregivers.caregiver', verbose_name='Bakıcı')),
                ('hasta', models.ForeignKey(db_column='HastaID', on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Bakıcı-Hasta Eşleştirmesi',
                'verbose_name_plural': 'Bakıcı-Hasta Eşleştirmeleri',
                'db_table': 'BakiciHastaEslestirme',
                'unique_together': {('bakici', 'hasta', 'baslangic_tarihi')},
            },
        ),
    ]
