# Generated by Django 4.2.7 on 2025-08-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0001_initial'),
    ]

    operations = [
    ]
