# Generated by Django 4.2.7 on 2025-08-04 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_patient_aktif_patient_allergies_patient_blood_type_and_more'),
        ('caregivers', '0002_auto_20250804_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Not')),
                ('note_type', models.CharField(choices=[('general', 'Genel'), ('medication', 'İlaç'), ('emergency', 'Acil Durum'), ('improvement', 'İyileşme'), ('concern', 'Endişe')], default='general', max_length=20, verbose_name='Not Tipi')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Acil')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Bakıcı Notu',
                'verbose_name_plural': 'Bakıcı Notları',
                'db_table': 'caregiver_notes',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverPatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atanma Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Son İletişim Tarihi')),
                ('contact_frequency', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], default='daily', max_length=20, verbose_name='İletişim Sıklığı')),
            ],
            options={
                'verbose_name': 'Bakıcı-Hasta Ataması',
                'verbose_name_plural': 'Bakıcı-Hasta Atamaları',
                'db_table': 'caregiver_patient_assignments',
            },
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='bakici_id',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='calisma_bolgeleri',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='maksimum_hasta_sayisi',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='saatlik_ucret',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='sertifika_numarasi',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='adres',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='calisma_saatleri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma Saatleri'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='degerlendirme_sayisi',
            field=models.IntegerField(default=0, verbose_name='Değerlendirme Sayısı'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiver',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiver',
            name='maas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maaş'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='musait_gunler',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Müsait Günler'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='sertifikalar',
            field=models.TextField(blank=True, help_text='Sahip olduğu sertifikaları belirtiniz', null=True, verbose_name='Sertifikalar'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='son_giris',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Giriş'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='toplam_puan',
            field=models.FloatField(default=0.0, verbose_name='Toplam Puan'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='uzmanlik_alanlari',
            field=models.TextField(blank=True, help_text='Yaşlı bakımı, engelli bakımı vb.', null=True, verbose_name='Uzmanlık Alanları'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='ad',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='deneyim',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 Yıl'), ('1-3', '1-3 Yıl'), ('3-5', '3-5 Yıl'), ('5-10', '5-10 Yıl'), ('10+', '10+ Yıl')], max_length=10, null=True, verbose_name='Deneyim'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='egitim_durumu',
            field=models.CharField(blank=True, choices=[('Lise', 'Lise'), ('OnLisans', 'Ön Lisans'), ('Lisans', 'Lisans'), ('YuksekLisans', 'Yüksek Lisans')], max_length=20, null=True, verbose_name='Eğitim Durumu'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='soyad',
            field=models.CharField(max_length=50, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='telefon_no',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bakici_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterModelTable(
            name='caregiver',
            table='caregivers',
        ),
        migrations.DeleteModel(
            name='CaregiverPatientMapping',
        ),
        migrations.AddField(
            model_name='caregiverpatientassignment',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_assignments', to='caregivers.caregiver', verbose_name='Bakıcı'),
        ),
        migrations.AddField(
            model_name='caregiverpatientassignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='patients.patient', verbose_name='Hasta'),
        ),
        migrations.AddField(
            model_name='caregivernote',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers.caregiver', verbose_name='Bakıcı'),
        ),
        migrations.AddField(
            model_name='caregivernote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Hasta'),
        ),
        migrations.AlterUniqueTogether(
            name='caregiverpatientassignment',
            unique_together={('caregiver', 'patient')},
        ),
    ]
